/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Info */
        get: operations["info_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Predict
         * @description Predict GDM probability + risk tier + top 5 SHAP contributions.
         *
         *     Tier rules (Option D — match Phase 2):
         *     - **Thấp**: có OGTT + prob < threshold
         *     - **Cao**: có OGTT + prob ≥ threshold
         *     - **Trung bình**: OGTT missing → recommend làm OGTT
         */
        post: operations["predict_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shap-local": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Shap Local
         * @description Full SHAP waterfall data — frontend dùng để render chart.
         *
         *     ⚠️ SHAP computation ~200-500ms/request. Cân nhắc cache nếu demo cùng lúc nhiều người.
         */
        post: operations["shap_local_shap_local_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History
         * @description List recent predictions. Source = Supabase nếu config, không thì mock.
         */
        get: operations["history_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PatientInput
         * @description Raw clinical features. None/missing OK cho OGTT, Sys BP, BMI, HDL.
         *
         *     Engineered features (MAP, BMI_category) KHÔNG nhận từ client — backend
         *     tự compute từ Sys BP/Dia BP/BMI để tránh inconsistent input.
         */
        PatientInput: {
            /**
             * Age
             * @description Tuổi (15-50)
             */
            Age: number;
            /** No Of Pregnancy */
            "No of Pregnancy": number;
            /** Gestation In Previous Pregnancy */
            "Gestation in previous Pregnancy": number;
            /** Bmi */
            BMI?: number | null;
            /** Hdl */
            HDL?: number | null;
            /**
             * Family History
             * @enum {integer}
             */
            "Family History": 0 | 1;
            /**
             * Unexplained Prenetal Loss
             * @enum {integer}
             */
            "unexplained prenetal loss": 0 | 1;
            /**
             * Large Child Or Birth Default
             * @enum {integer}
             */
            "Large Child or Birth Default": 0 | 1;
            /**
             * Pcos
             * @enum {integer}
             */
            PCOS: 0 | 1;
            /** Sys Bp */
            "Sys BP"?: number | null;
            /** Dia Bp */
            "Dia BP": number;
            /**
             * Ogtt
             * @description OGTT 2h, mg/dL. None nếu chưa đo
             */
            OGTT?: number | null;
            /** Hemoglobin */
            Hemoglobin: number;
            /**
             * Sedentary Lifestyle
             * @enum {integer}
             */
            "Sedentary Lifestyle": 0 | 1;
            /**
             * Prediabetes
             * @enum {integer}
             */
            Prediabetes: 0 | 1;
        };
        /** PredictResponse */
        PredictResponse: {
            /** Gdm Probability */
            gdm_probability: number;
            /**
             * Risk Level
             * @enum {string}
             */
            risk_level: "Thấp" | "Trung bình" | "Cao";
            /** Threshold Used */
            threshold_used: number;
            /** Has Ogtt */
            has_ogtt: boolean;
            /** Top5 Shap */
            top5_shap: components["schemas"]["ShapItem"][];
            /** Recommendation */
            recommendation?: string | null;
        };
        /** ShapItem */
        ShapItem: {
            /** Feature */
            feature: string;
            /** Value */
            value: number | null;
            /** Shap */
            shap: number;
            /**
             * Direction
             * @enum {string}
             */
            direction: "increase" | "decrease";
        };
        /** ShapLocalResponse */
        ShapLocalResponse: {
            /** Base Value */
            base_value: number;
            /** Predicted Probability */
            predicted_probability: number;
            /**
             * Risk Level
             * @enum {string}
             */
            risk_level: "Thấp" | "Trung bình" | "Cao";
            /** Features */
            features: components["schemas"]["ShapWaterfallItem"][];
        };
        /** ShapWaterfallItem */
        ShapWaterfallItem: {
            /** Feature */
            feature: string;
            /** Value */
            value: number | null;
            /** Shap */
            shap: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    info_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    predict_predict_post: {
        parameters: {
            query?: {
                /** @description Optional ID để lưu DB */
                patient_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shap_local_shap_local_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShapLocalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
